name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.1"
machine_id: 1
start_time: "2000-05-09"
client_url: "*"

log:
  level: "info"
  filename: "./web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
    host: "39.106.8.172"
    port: 13306
    user: "admin"
    password: "sinfotek"
    dbname: "sinfotek"
    max_idle_conns: 20
    max_conns: 100
redis:
    host: "39.106.8.172"
    port: 6379
    password: "sinfotek"
    dbname: 6
    pool_size: 100
etcd:
  endpoints:
    - "https://etcd.pawstickchief.com:2379"
  dial_timeout: 5000  # 超时时间，单位为毫秒
  ca_cert: "conf\ssl\etcd\ca.pem"
  cert_file: "conf\ssl\etcd\client.pem"
  key_file: "conf\ssl\etcd\client-key.pem"
  server_name: "etcd.pawstickchief.com"
  username: "addmin"
  password: "Mark1590"
file:
  filemaxsize: 2048
  savedir: "./static/upload/"
  httpurl: "http://127.0.0.1:8081"
  httpdir: "/static"

